---
- name: Test vmware esxi host inventory module
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Include secret files 
      include_vars:
        file: secrets.yml
        name: secret

    - name: Run vmware esxi host inventory module
      vmware_hosts_list: 
        vcenter="{{secret.vcenter}}" 
        username="{{secret.username}}" 
        password="{{secret.password}}"
      register: esxi_list

    #- name: Get vmware esxi host inventory module
    #  debug:
    #    msg: '{{ esxi_list.meta.hosts }}'

    - name: Gather vmware host facts from vCenter
      vmware_host_facts:
        hostname: "{{secret.vcenter}}" 
        username: "{{secret.username}}"
        password: "{{secret.password}}"
        esxi_hostname: "{{ item }}"
        validate_certs: no
      register: host_facts
      with_items: "{{esxi_list.meta.hosts}}"

    - name: Get vmware esxi host inventory module
      debug:
        msg: '{{ host_facts }}'
#ansible-playbook -i esxi_hosts_list.py playbook.yml