---
- name: Test vmware esxi host inventory module
  hosts: localhost
  gather_facts: false


  tasks:
    - name: Include secret files 
      include_vars:
        file: secrets.yml
        name: secret

    - name: Run vmware esxi host inventory module
      vmware_hosts_list: vcenter="{{secret.vcenter}}" username="{{secret.username}}" password="{{secret.password}}"
      register: esxi_list
      no_log: true

    - name: Get vmware esxi host inventory module
      debug:
        msg: '{{ esxi_list }}'


#ansible-playbook -i esxi_hosts_list.py playbook.yml